from isd_py_framework_sdk.base.Singleton import SingletonMetaclass
from isd_py_framework_sdk.message_logger.base.levels import LogLevelLiteral
from isd_py_framework_sdk.message_logger.base.LoggerBase import LoggerBase


class SingletonSystemLogger(LoggerBase, metaclass=SingletonMetaclass):
    def _initialize_manager(self):
        ...

    # --- Adapter 管理 ---------------------------------------------------------

    def register_adapter(self, adapter) -> None:
        """新增一個輸出 adapter。"""
        ...

    def unregister_adapter(self, adapter) -> None:
        """移除指定 adapter。"""
        ...

    def clear_adapters(self) -> None:
        """移除所有已註冊的 adapters。"""
        ...

    # --- 全域開關 -------------------------------------------------------------

    def enable_broadcast_msg(self): ...
    def disable_broadcast_msg(self): ...

    # --- 核心 log 方法 --------------------------------------------------------

    def shiny_log(self, message: str, level: LogLevelLiteral = "INFO"):
        """以 ✨ 裝飾輸出（adapter 端會同時加亮顏色）。"""
        ...

    def log(self, message: str, level: LogLevelLiteral = "INFO", shine: bool = False):
        """
            主要 log 方法。格式化後 fan-out 至所有已註冊的 adapters。
            各 adapter 依自身 level_filter 決定是否輸出。
        """
        ...

    # --- 快捷方法 -------------------------------------------------------------

    def debug(self, msg: str): ...
    def info(self, msg: str): ...
    def checkpoint(self, msg: str): ...
    def success(self, msg: str): ...
    def warning(self, msg: str): ...
    def error(self, msg: str): ...
    def critical(self, msg: str): ...
    def highlight(self, msg: str): ...

