from hyper_framework.events.EventBase import IEventBase as IEventBase, IParsEventBase as IParsEventBase
from typing import Callable, overload

class SingletonEventManager:
    def __new__(cls, *args, **kwargs): ...
    def __init__(self) -> None: ...
    @overload
    def RegisterEvent(self, event_class: type[IEventBase], callback: Callable[[], None]) -> None: ...
    @overload
    def RegisterEvent(self, event_class: type[IParsEventBase], callback: Callable[[IParsEventBase], None]) -> None: ...
    @overload
    def UnregisterEvent(self, event_class: type[IEventBase], callback: Callable[[], None]) -> None: ...
    @overload
    def UnregisterEvent(self, event_class: type[IParsEventBase], callback: Callable[[IParsEventBase], None]) -> None: ...
    def TriggerEvent(self, event_instance: IEventBase | IParsEventBase) -> None: ...
