"""
ISD Python Framework — Public API
"""
from ._version import __version__
from .base.Singleton import SingletonMetaclass
from .events.EventBase import IEventBase, IParsEventBase
from .events.EventManager import SingletonEventManager
from .events.DelayEventBusManager import DelayEventBusManager, IDelayEventBase, IDelayParsEventBase
from .events.MulticastCallback import MulticastCallback
from .message_logger.SingletonSystemLogger import SingletonSystemLogger
from .message_logger.adapters import (
    LoggerAdapterBase,
    DarkThemeTerminalAdapter,
    LightThemeTerminalAdapter,
    FileAdapter,
    TkinterAdapter,
    DarkThemeTkinterAdapter,
    LightThemeTkinterAdapter,
)

# ── decorators ────────────────────────────────────────────────────────────
from .helpers.decorators import (
    # legacy / profiling
    function_timer,
    timed_and_conditional_return,
    deprecated,
    battered,
    # profiling (new)
    log_call,
    count_calls,
    profile_memory,
    # lifecycle (new)
    experimental,
    removed_in,
    since,
    # control-flow
    retry,
    once,
    suppress_exceptions,
    throttle,
    timeout,
    # concurrency
    run_in_thread,
    synchronized,
    # ETL
    etl_step,
    log_record_count,
    checkpoint,
    skip_on_empty,
    idempotent_load,
    # validation
    not_none,
    validate_args,
    validate_return,
    ensure_type,
    clamp_return,
    non_empty_return,
    # GUI
    require_main_thread,
    debounce,
    gui_error_handler,
    disable_widget_during_run,
    run_after,
    # monitoring
    emit_metric,
    watchdog_ping,
    health_check,
    alert_on_failure,
    rate_limit,
    # AI / ML training
    training_step,
    log_epoch,
    inference_only,
    cache_predictions,
    grad_check,
    # architecture / SRP
    single_responsibility,
    layer,
    interface_method,
    abstract_implementation,
    no_side_effects,
    sealed,
    require_override,
    enforce_srp,
)

# ── exceptions ────────────────────────────────────────────────────────────
from .helpers.exceptions import (
    # legacy
    WrongOptionException,
    WrongImplementationException,
    UnhandledConditionError,
    RepeatedInitializationError,
    # lifecycle
    NotInitializedError,
    AlreadyDisposedError,
    TeardownError,
    # options
    MissingOptionError,
    OptionConflictError,
    OptionReadOnlyError,
    InvalidOptionValueError,
    # architecture
    AbstractMethodNotImplementedError,
    InterfaceContractError,
    CircularDependencyError,
    ComponentNotRegisteredError,
    ComponentAlreadyRegisteredError,
    LayerViolationError,
    # flow control
    ConditionNotMetError,
    ExecutionOrderError,
    FlowInterruptedError,
    PipelineCancelledError,
    StepAbortedError,
    MaxIterationsExceededError,
    # validation
    ConfigurationError,
    ValidationError,
    # runtime
    TimeoutExpiredError,
    DependencyError,
    ReadOnlyError,
    StateError,
    FeatureNotSupportedError,
    ResourceExhaustedError,
    # ETL
    DataExtractionError,
    DataTransformationError,
    DataLoadError,
    SchemaValidationError,
    MissingColumnError,
    DataTypeConversionError,
    DuplicateRecordError,
    EmptyDatasetError,
    DataCorruptionError,
    PartitionError,
    # GUI
    WidgetNotFoundError,
    UIStateError,
    RenderError,
    EventHandlerError,
    LayoutError,
    ThemeNotFoundError,
    WindowNotOpenError,
    ScreenResolutionError,
    # monitoring
    MetricCollectionError,
    ThresholdExceededError,
    WatchdogTriggeredError,
    HealthCheckFailedError,
    ProbeTimeoutError,
    ObservabilityError,
    SamplingError,
    # AI / ML training
    ModelNotFittedError,
    CheckpointNotFoundError,
    TrainingInterruptedError,
    HyperparameterError,
    DatasetSplitError,
    GradientExplosionError,
    GradientVanishingError,
    InferenceError,
    EpochLimitReachedError,
    ModelArchitectureError,
)

# ── assertions ────────────────────────────────────────────────────────────
from .helpers.assertions import (
    # legacy
    assert__is_str,
    assert__is_list_of_str,
    assert__is_list_of_list_of_str,
    assert__is_list_of_tuple_of_str,
    # type
    assert__is_int,
    assert__is_float,
    assert__is_number,
    assert__is_bool,
    assert__is_dict,
    assert__is_list,
    assert__is_tuple,
    assert__is_set,
    assert__is_callable,
    assert__is_none,
    assert__is_not_none,
    assert__is_instance,
    assert__is_subclass,
    assert__is_list_of_int,
    assert__is_list_of_float,
    assert__is_list_of_number,
    assert__is_dict_of_str_to_str,
    # value
    assert__is_positive,
    assert__is_non_negative,
    assert__is_not_empty,
    assert__in_range,
    assert__is_one_of,
    assert__matches_pattern,
    # collection
    assert__has_length,
    assert__min_length,
    assert__max_length,
    assert__all_keys_exist,
    assert__is_unique,
    assert__no_none_values,
    assert__contains_in_list,
    assert__contains_in_str,
    assert__contains_in_dataclass,
    assert__contains_in_object,
)

__all__ = [
    "__version__",
    # core
    "SingletonMetaclass",
    # events
    "IEventBase",
    "IParsEventBase",
    "SingletonEventManager",
    "IDelayEventBase",
    "IDelayParsEventBase",
    "DelayEventBusManager",
    "MulticastCallback",
    # logger
    "SingletonSystemLogger",
    "LoggerAdapterBase",
    "DarkThemeTerminalAdapter",
    "LightThemeTerminalAdapter",
    "FileAdapter",
    "TkinterAdapter",
    "DarkThemeTkinterAdapter",
    "LightThemeTkinterAdapter",
    # decorators — timing / legacy
    "function_timer",
    "timed_and_conditional_return",
    "deprecated",
    "battered",
    # decorators — profiling
    "log_call",
    "count_calls",
    "profile_memory",
    # decorators — lifecycle
    "experimental",
    "removed_in",
    "since",
    # decorators — control-flow
    "retry",
    "once",
    "suppress_exceptions",
    "throttle",
    "timeout",
    # decorators — concurrency
    "run_in_thread",
    "synchronized",
    # decorators — ETL
    "etl_step",
    "log_record_count",
    "checkpoint",
    "skip_on_empty",
    "idempotent_load",
    # decorators — validation
    "not_none",
    "validate_args",
    "validate_return",
    "ensure_type",
    "clamp_return",
    "non_empty_return",
    # decorators — GUI
    "require_main_thread",
    "debounce",
    "gui_error_handler",
    "disable_widget_during_run",
    "run_after",
    # decorators — monitoring
    "emit_metric",
    "watchdog_ping",
    "health_check",
    "alert_on_failure",
    "rate_limit",
    # decorators — AI / ML training
    "training_step",
    "log_epoch",
    "inference_only",
    "cache_predictions",
    "grad_check",
    # decorators — architecture / SRP
    "single_responsibility",
    "layer",
    "interface_method",
    "abstract_implementation",
    "no_side_effects",
    "sealed",
    "require_override",
    "enforce_srp",
    # exceptions — legacy
    "WrongOptionException",
    "WrongImplementationException",
    "UnhandledConditionError",
    "RepeatedInitializationError",
    # exceptions — lifecycle
    "NotInitializedError",
    "AlreadyDisposedError",
    "TeardownError",
    # exceptions — options
    "MissingOptionError",
    "OptionConflictError",
    "OptionReadOnlyError",
    "InvalidOptionValueError",
    # exceptions — architecture
    "AbstractMethodNotImplementedError",
    "InterfaceContractError",
    "CircularDependencyError",
    "ComponentNotRegisteredError",
    "ComponentAlreadyRegisteredError",
    "LayerViolationError",
    # exceptions — flow control
    "ConditionNotMetError",
    "ExecutionOrderError",
    "FlowInterruptedError",
    "PipelineCancelledError",
    "StepAbortedError",
    "MaxIterationsExceededError",
    # exceptions — validation
    "ConfigurationError",
    "ValidationError",
    # exceptions — runtime
    "TimeoutExpiredError",
    "DependencyError",
    "ReadOnlyError",
    "StateError",
    "FeatureNotSupportedError",
    "ResourceExhaustedError",
    # exceptions — ETL
    "DataExtractionError",
    "DataTransformationError",
    "DataLoadError",
    "SchemaValidationError",
    "MissingColumnError",
    "DataTypeConversionError",
    "DuplicateRecordError",
    "EmptyDatasetError",
    "DataCorruptionError",
    "PartitionError",
    # exceptions — GUI
    "WidgetNotFoundError",
    "UIStateError",
    "RenderError",
    "EventHandlerError",
    "LayoutError",
    "ThemeNotFoundError",
    "WindowNotOpenError",
    "ScreenResolutionError",
    # exceptions — monitoring
    "MetricCollectionError",
    "ThresholdExceededError",
    "WatchdogTriggeredError",
    "HealthCheckFailedError",
    "ProbeTimeoutError",
    "ObservabilityError",
    "SamplingError",
    # exceptions — AI / ML training
    "ModelNotFittedError",
    "CheckpointNotFoundError",
    "TrainingInterruptedError",
    "HyperparameterError",
    "DatasetSplitError",
    "GradientExplosionError",
    "GradientVanishingError",
    "InferenceError",
    "EpochLimitReachedError",
    "ModelArchitectureError",
    # assertions — type
    "assert__is_str",
    "assert__is_list_of_str",
    "assert__is_list_of_list_of_str",
    "assert__is_list_of_tuple_of_str",
    "assert__is_int",
    "assert__is_float",
    "assert__is_number",
    "assert__is_bool",
    "assert__is_dict",
    "assert__is_list",
    "assert__is_tuple",
    "assert__is_set",
    "assert__is_callable",
    "assert__is_none",
    "assert__is_not_none",
    "assert__is_instance",
    "assert__is_subclass",
    "assert__is_list_of_int",
    "assert__is_list_of_float",
    "assert__is_list_of_number",
    "assert__is_dict_of_str_to_str",
    # assertions — value
    "assert__is_positive",
    "assert__is_non_negative",
    "assert__is_not_empty",
    "assert__in_range",
    "assert__is_one_of",
    "assert__matches_pattern",
    # assertions — collection
    "assert__has_length",
    "assert__min_length",
    "assert__max_length",
    "assert__all_keys_exist",
    "assert__is_unique",
    "assert__no_none_values",
    "assert__contains_in_list",
    "assert__contains_in_str",
    "assert__contains_in_dataclass",
    "assert__contains_in_object",
]
